#!/usr/bin/bash
DURATION=${1:-1M}
echo ords-protocols DURATION=$DURATION
echo Demonstrate characteristics of different Tomcat protocols

ords-urls.py --protocol http -o 1110
ords-tps $DURATION "HTTP APR/native connector:                "

ords-urls.py --protocol http -o 1111
ords-tps $DURATION "HTTP Non blocking Java connector:         "

ords-urls.py --protocol http -o 1112
ords-tps $DURATION "HTTP Blocking Java connector:             "

ords-urls.py --protocol https -o 1210
ords-tps $DURATION "HTTPS APR/native connector (OpenSSL):     "

ords-urls.py --protocol https -o 1211
ords-tps $DURATION "HTTPS Non blocking Java connector (JSSE): "

ords-urls.py --protocol https -o 1212
ords-tps $DURATION "HTTPS Blocking Java connector (JSSE):     "

