#!/usr/bin/bash
. ords-lib
DURATION=${1:-1M}

echo ords-rev-proxy DURATION=$DURATION

#Allow duration as command line argment, default to one minute
killall -9 siege 2> /dev/null
#Hack, sometimes Hitch service doesn't start automatically when provisioning :(
#Start all instances now just in case
sudo systemctl start hitch@1.service > /dev/null
sudo systemctl start hitch@2.service > /dev/null
sudo systemctl start hitch@3.service > /dev/null

echo Run siege against for possible combinations of:
echo "Not Caching & Caching"
echo "GET & POST"
echo "HTTP & HTTPS"
echo "No Proxy (direct to Tomcat), httpd (Apache HTTP Server), nginx and varnish(&Hitch)"
echo Skipping impossible combinations 
echo Note occasionally siege may hang at end of test
echo "If that happens just kill it and re-run the test (sorry)"

for CACHE in off on
#for CACHE_MODE in cache_on
do 
   for METHOD in get post
#   for METHOD in GET
   do 
      for PROTOCOL in http https
#      for PROTOCOL in https
      do 
         echo "cache=$CACHE,method=$METHOD,protocol=$PROTOCOL"
         for REVERSE_PROXY in none httpd nginx varnish
#            for PROXY in proxy_nginx
         do
               #Skip invalid combos
            if [ "$CACHE" = "on" ]
            then
               if [ "$REVERSE_PROXY" = "none" ]
               then
                  continue          
               elif [ "$METHOD" = 'post' ] && [ "$REVERSE_PROXY" = 'httpd' ]
               then
                  continue 
               fi
            fi
            ords-urls.py --reverse_proxy $REVERSE_PROXY --protocol $PROTOCOL --cache $CACHE --method $METHOD -t manual
            DESCRIPTION=$(printf "%-8s" "$REVERSE_PROXY:")
            ords-tps $DURATION "$(printf "%-8s" "$REVERSE_PROXY:")"
         done
      done
   done
done

