#!/usr/bin/bash
DURATION=${1:-1M}
echo ords-auto-manual DURATION=$DURATION

echo Demonstrate difference between auto and manually generated REST services
echo Manually generated should exhibit higher transaction rate

ords-urls.py -t auto
ords-tps $DURATION "Auto REST:  "
ords-urls.py -t manual
ords-tps $DURATION "Manual REST:"
