#!/usr/bin/bash
ITERATIONS=${1:-3}
DURATION=${2:-1M}
echo ords-versions ITERATIONS=$ITERATIONS DURATION=$DURATION

for VERSION in 19.1 19.2
do 
   sudo systemctl stop tomcat.service
   #Redirect otherwise overwhelms output
   #Obviously change for troubleshooting :)
   echo About to install ORDS $VERSION
   sudo sh /vagrant/scripts/ords.sh $VERSION >/dev/null 2>&1 
   echo Installation Completed
   sudo systemctl start tomcat.service
   ords-urls.py -t auto
   echo "ORDS Version "$VERSION" Auto REST:"
   for (( i=1; i<=$ITERATIONS; i++ ))  
   do
      ords-tps $DURATION "Auto"
   done
   ords-urls.py -t manual
   echo "ORDS Version "$VERSION" Manual REST:"
   for (( i=1; i<=$ITERATIONS; i++ ))  
   do
      ords-tps $DURATION "Manual"
   done
done
