#!/usr/bin/bash
DURATION=${1:-10S}
ITERATIONS=${2:-30}

echo ords-warmup DURATION=$DURATION ITERATIONS=$ITERATIONS
echo Show throughput increases after Tomcat restart and ongoing variation 

#Build Siege urls.txt file
ords-urls.py
echo Restarting Tomcat
sudo systemctl restart tomcat.service
sleep 10

for (( i=0; i<$ITERATIONS; i++ ))  
do
    ords-tps $DURATION
done
