#!/usr/bin/bash
. ords-lib

ITERATIONS=${1:-30}
DURATION=${2:-10S}


echo ords-warmup ITERATIONS=$ITERATIONS DURATION=$DURATION
echo Show throughput increases after Tomcat restart and ongoing variation 

#Build Siege urls.txt file
ords-urls.py
echo Restarting Tomcat
sudo systemctl restart tomcat.service
sleep 10

for (( i=0; i<$ITERATIONS; i++ ))  
do
    ords-tps $DURATION
done
